# coding: utf-8
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
get_ipython().run_line_magic('clear', '')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
driver.find_element_by_xpath('/html/body/div/div[2]/div[12]/div/div[1]/div[1]/div[2]/textarea')
save = driver.find_element_by_xpath('/html/body/div/div[2]/div[12]/div/div[1]/div[1]/div[2]/textarea')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
get_ipython().run_line_magic('clear', '')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
get_ipython().run_line_magic('clear', '')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
upgrades = [driver.find_element_by_id('upgrades')]
len(upgrades)
len(driver.find_element_by_id())
len(driver.find_element_by_id('upgrades'))
len(driver.find_elements_by_id('upgrades'))
len(driver.find_elements_by_id('upgrades'))
len(driver.find_element_by_id('upgrades'))
len(driver.find_element_by_class_name('upgrades'))
driver.find_element_by_class_name('product unlocked enabled')
driver.find_element_by_class_name('product unlocked enabled')
driver.find_element_by_class_name('shimmer')
driver.find_element_by_class_name('a')
driver.find_element_by_class_name('product unlocked enabled')
driver.find_element_by_class_name('cc_banner-wrapper')
driver.find_elements_by_class_name(''product unlocked enabled)
driver.find_elements_by_class_name('product unlocked enabled')
driver.find_elements_by_xpath('//*[@id="product0"]')
driver.find_elements_by_xpath('//*[@id="product0"]')
driver.find_elements_by_class_name('product unlocked enabled')
driver.find_elements_by_class_name('enabled')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
driver.find_elements_by_class_name('enabled')
driver.find_elements_by_class_name('crate upgrade enabled')
#upgrades = [driver.find_element_by_id('upgrades
driver.find_elements_by_class_name('crate upgrade enabled')
#upgrades = [driver.find_element_by_id('upgrades
driver.find_elements_by_class_name('enabled')
len(driver.find_elements_by_class_name('enabled'))
len(driver.find_elements_by_class_name('enabled'))
len(driver.find_elements_by_class_name('enabled'))
len(driver.find_elements_by_class_name('enabled'))
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
c,ear
get_ipython().run_line_magic('clear', '')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
save()
save()
options = driver.find_element_by_id('prefsButton')
runfile('/Users/charlie/ML/Supervised Learning/Cookie Clicker/Selenium.py', wdir='/Users/charlie/ML/Supervised Learning/Cookie Clicker')
save()
exportSave = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[18]/div[2]/div[4]/div[3]/div/div[4]/a[1]')
exportSave = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[18]/div[2]/div[4]/div[3]/div/div[4]/a[1]')
exportSave = driver.find_element_by_xpath('/html/body/div/div[2]/div[18]/div[2]/div[4]/div[3]/div/div[4]/a[1]')
exportSave.click()
def save():
    try:
        options = driver.find_element_by_id('prefsButton')
        options.click()
        exportSave = driver.find_element_by_xpath('/html/body/div/div[2]/div[18]/div[2]/div[4]/div[3]/div/div[4]/a[1]')
        exportSave.click()
        options.click()
        save = driver.find_element_by_xpath('/html/body/div/div[2]/div[12]/div/div[1]/div[1]/div[2]/textarea').get_attribute('value')
        print(save)
        savefile = open("save.txt", "w")
        savefile.write(save)
        savefile.close()
        close1 = driver.find_element_by_xpath('/html/body/div/div[2]/div[12]/div/div[2]')
        close1.click()
        time.sleep(0.01)
        close2 = driver.find_element_by_xpath('/html/body/div/div[2]/div[18]/div[2]/div[4]/div[1]')
        close2.click()
    except:
        pass
        
save()
save = driver.find_element_by_xpath('/html/body/div/div[2]/div[12]/div/div[1]/div[1]/div[2]/textarea').get_attribute('value')
save
save()
